services:
  jmx:
    container_name: jmx
    ports:
      - "9200:9200"
    build:
      args:
        - EXPORTER_VERSION=${EXPORTER_VERSION} 
    environment:
      - HOSTNAME=${HOSTNAME}
      - MONITOR_ROLE_PASS=${MONITOR_ROLE_PASS}
      - PORT=${PORT}
      - SERVICE_PORT=${SERVICE_PORT}
    env_file:
      - .env
