services:
  amq-cli:
    container_name: amq-cli
    image: amq-cli
    restart: always
    pull_policy: never
    env_file:
      - config.env
    volumes:
    - ./testFiles/:/bindings/
    - ./github_token.sec:/config/github_token.sec
    - ./config.env:/config/config.env
