# Default values for ActiveMQ-JDBC.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

replicaCount: 2

image:
  repository: ghcr.io/thg-messaging/activemq-images/activemq-jdbc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.18.3-2024-06-18"

namespace: "amq"
brokerName: "amq-demo"
versionAMQ: 5.18.3

JDBCconfig:
  dbHost: "amq-db-postgres-rw.database.svc.cluster.local"
  #dbPort:
  dbName: "app"
  dbUser: "postgres"
  existingDbPasswordSecret: 
    namespace: "database"
    secretName: "amq-db-postgres-superuser"
    key: "password"
  createTables: "true"

schedulerSupport:
  enabled: "true"
  storageClass: "csi-cinder-sc-delete"
  size: 2Gi

debug:
  enabled: false

webUI:
  port: 8161
  type: ClusterIP

JMX:
  enabled: true
  type: ClusterIP
  port: 1099

metrics:
  enabled: true
  type: ClusterIP
  port: 12345

transportConnectors:
  openwire:
    enabled: true
    port: 61616
  amqp:
    enabled: true
    port: 5672
  stomp:
    enabled: true
    port: 61613
  mqtt:
    enabled: true
    port: 1883

jmx_exporter:
  hostname: localhost
  port: 1099
  monitor_role_pass: pa$$wd
  service_port: 9200
  exporter_version: 1.0.1

secrets:
  usersSecretName: "amq-external-users"
  groupSecretName: "amq-external-groups"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 2
    memory: 4G
  requests:
    cpu: 2
    memory: 2G

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ping-exporter:
  config:
    targets:
      - localhost

    dns:
      refresh: 2m15s
      nameserver: 1.1.1.1

    ping:
      interval: 2s
      timeout: 3s
      history-size: 42
      payload-size: 120
