---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-amq-scheduled-messages
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/apache-activemq-5.18.3/schedulerData"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-scheduled-messages
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi