# Default values for ActiveMQ-JDBC.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

replicaCount: 1

image:
  repository: ghcr.io/thg-messaging/activemq-images/activemq-jdbc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.16.5"

namespace: "amq-test"
brokerName: "amq-demo"

JDBCconfig:
  dbHost: "postgres-postgresql.amq-test.svc.cluster.local"
  #dbPort:
  dbName: "amq-test"
  dbUser: "postgres"
  existingDbPasswordSecret: 
    name: "postgres-postgresql"
    key: "postgres-password"
  createTables: "true"

webUI:
  port: 8161

JMX:
  enabled: true
  port: 1099

metrics:
  enabled: true
  port: 12345

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8161

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 2
    memory: 4G
  requests:
    cpu: 2
    memory: 2G

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
