apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq-charts.fullname" . }}
  labels:
    {{- include "activemq-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    name: {{ .Values.service.name }}
  selector:
    {{- include "activemq-charts.selectorLabels" . | nindent 4 }}
