---
apiVersion: v1
kind: Secret
metadata:
  name: "amq-admin-secret"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "amq-admin-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $amq-admin-secret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "amq-admin-secret") | default (randAlphaNum 32 | b64enc) }}
  amq-admin-secret: {{ $jwtSecret | quote }}
  # set $monitor-role-pass to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "monitor-role-pass") | default (randAlphaNum 32 | b64enc) }}
  monitor-role-pass: {{ $jwtSecret | quote }}
  # set $control-role-pass to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "control-role-pass") | default (randAlphaNum 32 | b64enc) }}
  control-role-pass: {{ $jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-details
data:
  db-password:  {{ index (lookup "v1" "Secret" .Values.JDBCconfig.existingDbPasswordSecret.namespace .Values.JDBCconfig.existingDbPasswordSecret.secretName).data .Values.JDBCconfig.existingDbPasswordSecret.key }}