apiVersion: v1
kind: Secret
metadata:
  name: "amq-admin-secret"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "amq-admin-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $amq-admin-secret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "amq-admin-secret") | default (randAlphaNum 32 | b64enc) }}
  amq-admin-secret: {{ $jwtSecret | quote }}
