---
apiVersion: v1
kind: Secret
metadata:
  name: db-details
data:
  db-password:  {{ index (lookup "v1" "Secret" .Values.JDBCconfig.existingDbPasswordSecret.namespace .Values.JDBCconfig.existingDbPasswordSecret.secretName).data .Values.JDBCconfig.existingDbPasswordSecret.key }}