replicaCount: 1

image:
  repository: ghcr.io/thg-messaging/activemq-images/activemq
  pullPolicy: IfNotPresent
  tag: "5.16.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP

ingress:
  enabled: false
  className: ""
  labels: {}
  annotations: {}
  paths: [/]
  hosts: []
  tls: []

#ingress:
#  enabled: true
#  className: ""
#  annotations: {}
#  hosts:
#    - host: ""
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

#resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

#tolerations: []

#affinity: {}
