replicaCount: 1

image:
  repository: ghcr.io/thg-messaging/activemq-images/activemq
  pullPolicy: IfNotPresent
  tag: "5.16.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP

ingress:
  enabled: true
  className: ""
  labels: {}
  annotations: {}
  paths: [/]
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

#tolerations: []

#affinity: {}
