replicaCount: 1

image:
  repository: ghcr.io/thg-messaging/activemq-images/activemq
  pullPolicy: IfNotPresent
  tag: "5.16.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP

ingress:
  enabled: true
  className: ""
  labels: {}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  paths:
          - path: /admin/(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 8161
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: openwire
                port:
                  number: 61616
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

#tolerations: []

#affinity: {}
