name: Build a Docker image to deploy, run, or push to a registry.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        cd ActiveMQ-classic/5.16.5 && docker build . --file Dockerfile --tag activemq-5.16.5
