name: Build ActiveMQ docker image

on: 
  push:
    branches: [ "main" ]
    tags: [ 'amq-*.*.*' ]
    paths: ['ActiveMQ-classic/5.18.5-jdbc/**']
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, labeled, unlabeled ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/ActiveMQ-JDBC

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set Release Version
        run: |
          echo "BUILD_VERSION=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Rule 1: For a push to the main branch, create tag '5.18.5-${{ env.BUILD_VERSION }}' as previously
            type=raw,value=5.18.5-${{ env.BUILD_VERSION }},enable=${{ github.ref == 'refs/heads/main' }}
            # Rule 2: For a Git Tag (e.g., amq-1.2.3), create tag 'amq-1.2.3'
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/amq-') }}
            # Rule 3: For a labeled PR, create one combined tag
            type=raw,value=5.18.5-${{ env.BUILD_VERSION }}-pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}

      - name: Extract Docker metadata
        id: meta-jmx
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-jmx
          tags: 1.0.1-${{ env.BUILD_VERSION }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./ActiveMQ-classic/5.18.5-jdbc/amq_dockerImage
          push: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'build-image-for-testing') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PROM_EXPORTER_VERSION=0.20.0
            POSTGRESQL_JDBC_DRIVER=42.7.3
            AMQ_VERSION=5.18.5
            HIKARICP_VERSION=5.1.0
            JMX_EXPORTER_VERSION=1.2.0

      - name: Build and push Docker image
        id: build-and-push-jmx
        uses: docker/build-push-action@v3
        with:
          context: ./ActiveMQ-classic/5.18.5-jdbc/jmx_dockerImage
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-jmx.outputs.tags }}
          labels: ${{ steps.meta-jmx.outputs.labels }}
          build-args: |
            EXPORTER_VERSION=1.0.1
