name: trivy

on:
  workflow_run:
    workflows: ["Build ActiveMQ docker image"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-24.04"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test vars
        run: echo "${{ inputs.version }}""

      - name: Build an image from Dockerfile
        run: |
          cd ActiveMQ-classic/5.18.5-jdbc/amq_dockerImage && docker build -t ghcr.io/thg-messaging/activemq-images/activemq-jdbc:${{ github.sha }} $(cat versions.env | sed 's@^@--build-arg @g' | paste -s -d " ") .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/thg-messaging/activemq-images/activemq-jdbc:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
